# Generated by Django 4.2.5 on 2023-09-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_storages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
