# Generated by Django 4.2.5 on 2023-09-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100000000000)),
                ('shelf', models.CharField(default='', max_length=100)),
                ('good_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
                ('warehouse', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
