# Generated by Django 4.2.5 on 2023-09-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='normalImage',
            field=models.ImageField(default=None, upload_to='normal_images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='segmentedImage',
            field=models.ImageField(default=None, upload_to='segmented_images'),
        ),
    ]
