# Generated by Django 4.2.5 on 2023-09-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_warehouse_normalimage_warehouse_segmentedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='normalImage',
            field=models.ImageField(default='default-profile-image-png-1-Transparent-Images.png', upload_to='normal_images'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='segmentedImage',
            field=models.ImageField(default='default-profile-image-png-1-Transparent-Images.png', upload_to='segmented_images'),
        ),
    ]
