# Generated by Django 4.2.5 on 2023-09-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_warehouse_normalimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='normalImage',
            field=models.ImageField(default='default-profile-image-png-1-Transparent-Images.png', null=True, upload_to='normal_images'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='segmentedImage',
            field=models.ImageField(default='default-profile-image-png-1-Transparent-Images.png', null=True, upload_to='segmented_images'),
        ),
    ]
